export type HarmCategory =
	| 'HARM_CATEGORY_UNSPECIFIED'
	| 'HARM_CATEGORY_DEROGATORY'
	| 'HARM_CATEGORY_TOXICITY'
	| 'HARM_CATEGORY_VIOLENCE'
	| 'HARM_CATEGORY_SEXUAL'
	| 'HARM_CATEGORY_MEDICAL'
	| 'HARM_CATEGORY_DANGEROUS'
	| 'HARM_CATEGORY_HARASSMENT'
	| 'HARM_CATEGORY_HATE_SPEECH'
	| 'HARM_CATEGORY_SEXUALLY_EXPLICIT'
	| 'HARM_CATEGORY_DANGEROUS_CONTENT'
	| 'HARM_CATEGORY_CIVIC_INTEGRITY';

export type HarmProbability =
	| 'HARM_PROBABILITY_UNSPECIFIED'
	| 'NEGLIGIBLE'
	| 'LOW'
	| 'MEDIUM'
	| 'HIGH';

export type HarmBlockThreshold =
	| 'HARM_BLOCK_THRESHOLD_UNSPECIFIED'
	| 'BLOCK_LOW_AND_ABOVE'
	| 'BLOCK_MEDIUM_AND_ABOVE'
	| 'BLOCK_ONLY_HIGH'
	| 'BLOCK_NONE'
	| 'OFF';

export type Modality = 'MODALITY_UNSPECIFIED' | 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO' | 'DOCUMENT';

export type ResponseModality = 'MODALITY_UNSPECIFIED' | 'TEXT' | 'IMAGE' | 'AUDIO';

export type MediaResolution =
	| 'MEDIA_RESOLUTION_UNSPECIFIED'
	| 'MEDIA_RESOLUTION_LOW'
	| 'MEDIA_RESOLUTION_MEDIUM'
	| 'MEDIA_RESOLUTION_HIGH';

export type ServiceTier = 'unspecified' | 'standard' | 'flex' | 'priority';

export type ThinkingLevel = 'THINKING_LEVEL_UNSPECIFIED' | 'MINIMAL' | 'LOW' | 'MEDIUM' | 'HIGH';

export type FinishReason =
	| 'FINISH_REASON_UNSPECIFIED'
	| 'STOP'
	| 'MAX_TOKENS'
	| 'SAFETY'
	| 'RECITATION'
	| 'LANGUAGE'
	| 'OTHER'
	| 'BLOCKLIST'
	| 'PROHIBITED_CONTENT'
	| 'SPII'
	| 'MALFORMED_FUNCTION_CALL'
	| 'IMAGE_SAFETY'
	| 'IMAGE_PROHIBITED_CONTENT'
	| 'IMAGE_OTHER'
	| 'NO_IMAGE'
	| 'IMAGE_RECITATION'
	| 'UNEXPECTED_TOOL_CALL'
	| 'TOO_MANY_TOOL_CALLS'
	| 'MISSING_THOUGHT_SIGNATURE'
	| 'MALFORMED_RESPONSE';

export type BlockReason =
	| 'BLOCK_REASON_UNSPECIFIED'
	| 'SAFETY'
	| 'OTHER'
	| 'BLOCKLIST'
	| 'PROHIBITED_CONTENT'
	| 'IMAGE_SAFETY';

export type ModelStage =
	| 'MODEL_STAGE_UNSPECIFIED'
	| 'EXPERIMENTAL'
	| 'PREVIEW'
	| 'STABLE'
	| 'LEGACY'
	| 'RETIRED';
