import { ARTICLE_STATUS } from './article-status';

export const ARTICLE_STATUS_TRANSITIONS: Record<string, string[]> = {
	[ARTICLE_STATUS.DRAFT]: [ARTICLE_STATUS.PUBLISHED, ARTICLE_STATUS.ARCHIVED],
	[ARTICLE_STATUS.PUBLISHED]: [ARTICLE_STATUS.ARCHIVED],
	[ARTICLE_STATUS.ARCHIVED]: [],
};
